name: base
channels:
  - defaults
dependencies:
  - cython=0.29.32
  - cytoolz=0.11.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - jellyfish=0.9.0
  - libgcc-ng=11.2.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - networkx=2.8.4
  - pip=22.2.2
  - python=3.9.13
  - tbb=2021.6.0
  - pip:
    - dgl==1.0.1
    - keras==2.12.0
    - numpy==1.24.3
    - torch==1.13.1
